### ISSUE TITLE
Incorrect manual pick in Sudbury

### ISSUE THREAD

**Issue by ozw4** [mila-iqia/hardpicks#3]
I run the notebook code, Sudbury site got a checksum validation failure.
And when I skipped the validation check, I found some manual picks are obviously incorrect as below image.

![image](https://user-images.githubusercontent.com/18514139/184560507-4e035461-6840-4581-aba7-5c5d0a9f9151.png)

Is there a reason I'm getting  incorrect picks?

I dowloaded data from https://d3sakqnghgsk6x.cloudfront.net/Sudbury_3D/Sudbury3D_all_shots_2s.hdf.xz

**Comment by plstcharles** [comment]
Hello! Thanks for the report, we will be taking a look at this over the next few days --- some of our team members are on vacation, but we will try to provide an update before the end of next week, or as soon as possible.

**Comment by gbellefl** [comment]
Hello,
As pointed out, some shot gathers in the Sudbury dataset have misregistered first breaks. A second issue is related to some shots fired directly at the surface due to drill rig access problems to specific shot locations during data acquisition. Those shot gathers have a slightly different character and are out-of-distribution with respect to the rest of the data. For both issues, the first breaks of problematic shot gathers (132 shot gathers in total) were reset to 0 ms. This preprocessing step was applied for the Sudbury data in St-Charles et al. (2021) but not in the notebook provided in the GitHub repository (apologies).

A new file with the modified first breaks is now available for download for Sudbury (see Download link in README.md). Values assigned to variables hdf5_file_name and  md5_checksum have also been changed for Sudbury in the notebook.

**Comment by ozw4** [comment]
I confirmed that the new file is correct.
I appreciate your kind response.
